name: Build and deploy Node.js app to Azure Web App - miracoCallCenter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present

      - name: Upload build artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'miracoCallCenter'
          slot-name: 'Production'
          package: dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CAECECFFFD47472DB97F8CA99D377B5E }}
